In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant",30)

[24, 4]

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[29, 3], [24, 4], [22, 17], [1, 22, 3], [14, 12, 20], [22, 3], [12, 12, 16], [15, 7], [15, 8], [25, 24]]


In [ ]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[29  3  0  0]
 [24  4  0  0]
 [22 17  0  0]
 [ 1 22  3  0]
 [14 12 20  0]
 [22  3  0  0]
 [12 12 16  0]
 [15  7  0  0]
 [15  8  0  0]
 [25 24  0  0]]


In [ ]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
print(X.shape)
print(y.shape)

(10, 4)
(10,)


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, y, epochs=50, verbose=0)

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 262ms/step - loss: 0.6551 - accuracy: 0.9000


0.8999999761581421

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
weights[13]

array([ 0.04034619,  0.04296923,  0.04687915,  0.00638105, -0.04339729],
      dtype=float32)

In [ ]:
weights[4]

array([ 0.07735493,  0.01486685,  0.01129585, -0.00575511,  0.06482093],
      dtype=float32)

In [ ]:
weights[16]

array([-0.01278213,  0.02285254,  0.09630153,  0.01626041,  0.09428931],
      dtype=float32)